const mongoose = require('mongoose');
const dotenv = require('dotenv');
dotenv.config();

const User = require('./models/User');
const Tour = require('./models/Tour');
const Booking = require('./models/Booking');

const seed = async () => {
  await mongoose.connect(process.env.MONGODB_URI);
  console.log('Connected to DB for seeding...');

  // Clear existing data
  await User.deleteMany({});
  await Tour.deleteMany({});
  await Booking.deleteMany({});

  // Create admin and users
  const admin = await User.create({
    name: 'Admin User',
    email: 'admin@tourpro.com',
    password: 'admin123',
    role: 'admin',
    phone: '+1-555-0100',
    isActive: true
  });

  const user1 = await User.create({
    name: 'John Doe',
    email: 'john@example.com',
    password: 'user123',
    role: 'user',
    phone: '+1-555-0101'
  });

  const user2 = await User.create({
    name: 'Jane Smith',
    email: 'jane@example.com',
    password: 'user123',
    role: 'user',
    phone: '+1-555-0102'
  });

  // Create sample tours
  const tours = await Tour.insertMany([
    {
      title: 'Amazing Bali Getaway',
      description: 'Experience the magic of Bali with stunning temples, rice terraces, and pristine beaches. This well-planned itinerary balances adventure, culture, and relaxation.',
      destination: 'Bali',
      country: 'Indonesia',
      duration: { days: 7, nights: 6 },
      price: { adult: 1299, child: 799, currency: 'USD' },
      maxGroupSize: 15,
      difficulty: 'Easy',
      category: 'Beach',
      inclusions: ['Hotel accommodation', 'Daily breakfast', 'Airport transfers', 'Temple visits', 'Rice terrace trek'],
      exclusions: ['International flights', 'Visa fees', 'Personal expenses', 'Travel insurance'],
      itinerary: [
        { day: 1, title: 'Arrival & Kuta Beach', description: 'Arrive in Bali, check-in and relax at Kuta Beach.', accommodation: 'Kuta Beach Hotel' },
        { day: 2, title: 'Ubud Cultural Tour', description: 'Visit the Tegalalang Rice Terrace and Sacred Monkey Forest.', accommodation: 'Ubud Villa' },
        { day: 3, title: 'Temple Trail', description: 'Explore Tanah Lot and Uluwatu temples with sunset views.', accommodation: 'Ubud Villa' }
      ],
      coverImage: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800',
      images: ['https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800'],
      startDates: [new Date('2025-03-15'), new Date('2025-04-10'), new Date('2025-05-05')],
      availableSlots: 12,
      rating: 4.5,
      ratingsCount: 10,
      featured: true,
      status: 'Active',
      createdBy: admin._id
    },
    {
      title: 'Swiss Alps Adventure',
      description: 'Explore the majestic Swiss Alps with world-class skiing, hiking, and breathtaking mountain scenery. An unforgettable alpine experience.',
      destination: 'Interlaken',
      country: 'Switzerland',
      duration: { days: 8, nights: 7 },
      price: { adult: 3499, child: 2200, currency: 'USD' },
      maxGroupSize: 12,
      difficulty: 'Challenging',
      category: 'Mountain',
      inclusions: ['4-star hotel', 'Ski passes', 'Guided hikes', 'Cable car rides', 'All breakfasts & dinners'],
      exclusions: ['Flights', 'Ski equipment rental', 'Travel insurance', 'Alcohol'],
      coverImage: 'https://images.unsplash.com/photo-1531400158697-005a3d415b4a?w=800',
      images: ['https://images.unsplash.com/photo-1531400158697-005a3d415b4a?w=800'],
      startDates: [new Date('2025-02-20'), new Date('2025-03-10')],
      availableSlots: 8,
      rating: 4.8,
      ratingsCount: 9,
      featured: true,
      status: 'Active',
      createdBy: admin._id
    },
    {
      title: 'African Safari Experience',
      description: 'Witness the Great Migration and explore the vast Serengeti. Encounter the Big Five in their natural habitat on this unforgettable safari.',
      destination: 'Serengeti',
      country: 'Tanzania',
      duration: { days: 10, nights: 9 },
      price: { adult: 4999, child: 3500, currency: 'USD' },
      maxGroupSize: 8,
      difficulty: 'Moderate',
      category: 'Wildlife',
      inclusions: ['Luxury safari lodge', 'All meals', 'Game drives', 'Park fees', 'English guide'],
      exclusions: ['International flights', 'Visa', 'Yellow fever vaccination', 'Tips'],
      coverImage: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800',
      images: ['https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800'],
      startDates: [new Date('2025-07-01'), new Date('2025-08-15')],
      availableSlots: 6,
      rating: 5.0,
      ratingsCount: 8,
      featured: true,
      status: 'Active',
      createdBy: admin._id
    },
    {
      title: 'Kyoto Cultural Immersion',
      description: 'Explore ancient temples, zen gardens, and geisha districts in Japan\'s cultural capital. Enjoy tea ceremonies and authentic Japanese hospitality.',
      destination: 'Kyoto',
      country: 'Japan',
      duration: { days: 6, nights: 5 },
      price: { adult: 2299, child: 1500, currency: 'USD' },
      maxGroupSize: 10,
      difficulty: 'Easy',
      category: 'Cultural',
      inclusions: ['Ryokan accommodation', 'Breakfast included', 'Temple passes', 'Tea ceremony', 'Kimono rental'],
      exclusions: ['Flights', 'Lunch & dinner', 'Personal shopping'],
      coverImage: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800',
      images: ['https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800'],
      startDates: [new Date('2025-04-01'), new Date('2025-11-01')],
      availableSlots: 9,
      rating: 4.7,
      ratingsCount: 11,
      featured: false,
      status: 'Active',
      createdBy: admin._id
    },
    {
      title: 'Maldives Paradise Escape',
      description: 'Enjoy ultimate luxury in the crystal-clear waters of the Maldives. Private overwater bungalows, world-class snorkeling, and total serenity.',
      destination: 'Malé Atoll',
      country: 'Maldives',
      duration: { days: 5, nights: 4 },
      price: { adult: 3999, child: 2800, currency: 'USD' },
      maxGroupSize: 6,
      difficulty: 'Easy',
      category: 'Honeymoon',
      inclusions: ['Overwater villa', 'All-inclusive meals', 'Snorkeling gear', 'Speedboat transfers', 'Spa treatment'],
      exclusions: ['International flights', 'Alcohol upgrades', 'Excursions'],
      coverImage: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800',
      images: ['https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800'],
      startDates: [new Date('2025-02-14'), new Date('2025-06-01')],
      availableSlots: 4,
      rating: 5.0,
      ratingsCount: 7,
      featured: true,
      status: 'Active',
      createdBy: admin._id
    },
    {
      title: 'New York City Explorer',
      description: 'Discover the city that never sleeps. From Times Square to Central Park, museums to Broadway shows — the ultimate NYC experience.',
      destination: 'New York City',
      country: 'USA',
      duration: { days: 5, nights: 4 },
      price: { adult: 1899, child: 1200, currency: 'USD' },
      maxGroupSize: 20,
      difficulty: 'Easy',
      category: 'City',
      inclusions: ['Hotel in Midtown', 'City pass', 'Guided tours', 'Airport transfers', 'Welcome dinner'],
      exclusions: ['Flights', 'Broadway tickets', 'Meals (except dinner)'],
      coverImage: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800',
      images: ['https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800'],
      startDates: [new Date('2025-03-01'), new Date('2025-09-15')],
      availableSlots: 18,
      rating: 4.4,
      ratingsCount: 12,
      featured: false,
      status: 'Active',
      createdBy: admin._id
    },
    {
      title: 'Paris Icons & Culture Tour',
      description: 'Experience the romance of Paris with iconic landmarks, world-class art, and charming neighborhoods, from the Eiffel Tower to Montmartre.',
      destination: 'Paris',
      country: 'France',
      duration: { days: 6, nights: 5 },
      price: { adult: 2199, child: 1399, currency: 'USD' },
      maxGroupSize: 18,
      difficulty: 'Easy',
      category: 'City',
      inclusions: ['4-star hotel', 'Daily breakfast', 'Louvre guided visit', 'Seine cruise', 'City transport pass'],
      exclusions: ['Flights', 'Lunch and dinner', 'Visa fees'],
      coverImage: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800',
      images: ['https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800'],
      startDates: [new Date('2025-04-18'), new Date('2025-10-05')],
      availableSlots: 16,
      rating: 4.6,
      ratingsCount: 14,
      featured: true,
      status: 'Active',
      createdBy: admin._id
    },
    {
      title: 'Rome Ancient Wonders',
      description: 'Walk through the Eternal City and uncover legendary history at the Colosseum, Roman Forum, and Vatican City with expert local guides.',
      destination: 'Rome',
      country: 'Italy',
      duration: { days: 6, nights: 5 },
      price: { adult: 2099, child: 1299, currency: 'USD' },
      maxGroupSize: 16,
      difficulty: 'Easy',
      category: 'Cultural',
      inclusions: ['Central hotel', 'Breakfast', 'Colosseum entry', 'Vatican museums pass', 'Walking tours'],
      exclusions: ['Flights', 'Tourist tax', 'Travel insurance'],
      coverImage: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800',
      images: ['https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800'],
      startDates: [new Date('2025-05-10'), new Date('2025-09-20')],
      availableSlots: 14,
      rating: 4.7,
      ratingsCount: 13,
      featured: false,
      status: 'Active',
      createdBy: admin._id
    },
    {
      title: 'Dubai Luxury Escape',
      description: 'Enjoy futuristic cityscapes, desert adventures, and luxury shopping in Dubai with curated experiences for comfort and excitement.',
      destination: 'Dubai',
      country: 'UAE',
      duration: { days: 5, nights: 4 },
      price: { adult: 2399, child: 1499, currency: 'USD' },
      maxGroupSize: 20,
      difficulty: 'Easy',
      category: 'City',
      inclusions: ['5-star hotel', 'Breakfast', 'Desert safari', 'Burj Khalifa ticket', 'Airport transfers'],
      exclusions: ['Flights', 'Personal shopping', 'Optional attractions'],
      coverImage: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800',
      images: ['https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800'],
      startDates: [new Date('2025-03-22'), new Date('2025-11-12')],
      availableSlots: 20,
      rating: 4.5,
      ratingsCount: 15,
      featured: true,
      status: 'Active',
      createdBy: admin._id
    },
    {
      title: 'London Royal Heritage Tour',
      description: 'Explore London’s rich heritage with palace visits, river cruises, museums, and classic neighborhoods filled with character and history.',
      destination: 'London',
      country: 'United Kingdom',
      duration: { days: 6, nights: 5 },
      price: { adult: 2299, child: 1499, currency: 'USD' },
      maxGroupSize: 18,
      difficulty: 'Easy',
      category: 'City',
      inclusions: ['Hotel stay', 'Breakfast', 'Thames cruise', 'Guided city tour', 'Public transport card'],
      exclusions: ['Flights', 'Visa fees', 'Lunch and dinner'],
      coverImage: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800',
      images: ['https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800'],
      startDates: [new Date('2025-04-08'), new Date('2025-08-28')],
      availableSlots: 17,
      rating: 4.4,
      ratingsCount: 11,
      featured: false,
      status: 'Active',
      createdBy: admin._id
    },
    {
      title: 'Cairo & Pyramids Discovery',
      description: 'Travel through ancient Egyptian history with visits to the Great Pyramids, the Sphinx, and world-renowned museums in Cairo.',
      destination: 'Cairo',
      country: 'Egypt',
      duration: { days: 7, nights: 6 },
      price: { adult: 1999, child: 1250, currency: 'USD' },
      maxGroupSize: 15,
      difficulty: 'Moderate',
      category: 'Cultural',
      inclusions: ['4-star hotel', 'Breakfast & selected dinners', 'Pyramid entry', 'Museum tickets', 'Guided excursions'],
      exclusions: ['Flights', 'Visa fees', 'Tips'],
      coverImage: 'https://images.unsplash.com/photo-1539650116574-75c0c6d73f2e?w=800',
      images: ['https://images.unsplash.com/photo-1539650116574-75c0c6d73f2e?w=800'],
      startDates: [new Date('2025-02-25'), new Date('2025-10-18')],
      availableSlots: 13,
      rating: 4.6,
      ratingsCount: 10,
      featured: true,
      status: 'Active',
      createdBy: admin._id
    },
    {
      title: 'Santorini Sunset Escape',
      description: 'Relax in the stunning Greek islands with whitewashed villages, blue domes, dramatic cliffs, and unforgettable sunsets.',
      destination: 'Santorini',
      country: 'Greece',
      duration: { days: 5, nights: 4 },
      price: { adult: 2099, child: 1350, currency: 'USD' },
      maxGroupSize: 12,
      difficulty: 'Easy',
      category: 'Honeymoon',
      inclusions: ['Boutique hotel', 'Breakfast', 'Catamaran cruise', 'Winery visit', 'Airport transfers'],
      exclusions: ['Flights', 'Lunch and dinner', 'Travel insurance'],
      coverImage: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800',
      images: ['https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800'],
      startDates: [new Date('2025-05-02'), new Date('2025-09-02')],
      availableSlots: 10,
      rating: 4.9,
      ratingsCount: 9,
      featured: true,
      status: 'Active',
      createdBy: admin._id
    },
    {
      title: 'Machu Picchu Trek Adventure',
      description: 'Journey to Peru’s legendary Incan citadel through scenic mountain routes and ancient sites with expert local guides.',
      destination: 'Machu Picchu',
      country: 'Peru',
      duration: { days: 8, nights: 7 },
      price: { adult: 2899, child: 1899, currency: 'USD' },
      maxGroupSize: 10,
      difficulty: 'Challenging',
      category: 'Adventure',
      inclusions: ['Lodge stays', 'Daily meals on trek', 'Train tickets', 'Entry permits', 'Mountain guide'],
      exclusions: ['International flights', 'Personal trekking gear', 'Tips'],
      coverImage: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800',
      images: ['https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800'],
      startDates: [new Date('2025-06-10'), new Date('2025-09-25')],
      availableSlots: 8,
      rating: 4.8,
      ratingsCount: 12,
      featured: true,
      status: 'Active',
      createdBy: admin._id
    },
    {
      title: 'Petra & Jordan Highlights',
      description: 'Visit the rose-red city of Petra, the dramatic Wadi Rum desert, and Jordan’s timeless heritage in one epic itinerary.',
      destination: 'Petra',
      country: 'Jordan',
      duration: { days: 7, nights: 6 },
      price: { adult: 2499, child: 1599, currency: 'USD' },
      maxGroupSize: 14,
      difficulty: 'Moderate',
      category: 'Cultural',
      inclusions: ['Hotel stays', 'Breakfast', 'Petra day pass', 'Wadi Rum jeep tour', 'Guided excursions'],
      exclusions: ['Flights', 'Visa fees', 'Optional activities'],
      coverImage: 'https://images.unsplash.com/photo-1579606032821-4e6161c81bd3?w=800',
      images: ['https://images.unsplash.com/photo-1579606032821-4e6161c81bd3?w=800'],
      startDates: [new Date('2025-03-30'), new Date('2025-10-10')],
      availableSlots: 12,
      rating: 4.7,
      ratingsCount: 10,
      featured: false,
      status: 'Active',
      createdBy: admin._id
    },
    {
      title: 'Sydney Coastal Explorer',
      description: 'Discover Sydney’s iconic harbor, beaches, and vibrant neighborhoods with the perfect blend of city energy and coastal relaxation.',
      destination: 'Sydney',
      country: 'Australia',
      duration: { days: 6, nights: 5 },
      price: { adult: 2599, child: 1699, currency: 'USD' },
      maxGroupSize: 18,
      difficulty: 'Easy',
      category: 'City',
      inclusions: ['Harbor-view hotel', 'Breakfast', 'Opera House tour', 'Blue Mountains day trip', 'Airport transfers'],
      exclusions: ['Flights', 'Lunch and dinner', 'Visa fees'],
      coverImage: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800',
      images: ['https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800'],
      startDates: [new Date('2025-04-25'), new Date('2025-12-01')],
      availableSlots: 16,
      rating: 4.5,
      ratingsCount: 9,
      featured: false,
      status: 'Active',
      createdBy: admin._id
    },
    {
      title: 'Cape Town Scenic Journey',
      description: 'Experience South Africa’s coastal beauty, vineyards, and wildlife around Cape Town with panoramic drives and cultural encounters.',
      destination: 'Cape Town',
      country: 'South Africa',
      duration: { days: 7, nights: 6 },
      price: { adult: 2399, child: 1499, currency: 'USD' },
      maxGroupSize: 15,
      difficulty: 'Moderate',
      category: 'Wildlife',
      inclusions: ['Hotel stays', 'Breakfast', 'Cape Peninsula tour', 'Wine estate visit', 'Penguin colony entry'],
      exclusions: ['Flights', 'Personal expenses', 'Travel insurance'],
      coverImage: 'https://images.unsplash.com/photo-1576485290814-1c72aa4bbb8e?w=800',
      images: ['https://images.unsplash.com/photo-1576485290814-1c72aa4bbb8e?w=800'],
      startDates: [new Date('2025-05-14'), new Date('2025-11-05')],
      availableSlots: 12,
      rating: 4.6,
      ratingsCount: 8,
      featured: false,
      status: 'Active',
      createdBy: admin._id
    },
    {
      title: 'Istanbul East Meets West',
      description: 'Explore Istanbul’s grand mosques, bustling bazaars, and Bosphorus beauty where European and Asian cultures blend seamlessly.',
      destination: 'Istanbul',
      country: 'Turkey',
      duration: { days: 6, nights: 5 },
      price: { adult: 1899, child: 1199, currency: 'USD' },
      maxGroupSize: 16,
      difficulty: 'Easy',
      category: 'Cultural',
      inclusions: ['Hotel stay', 'Breakfast', 'Hagia Sophia visit', 'Bosphorus cruise', 'Old city walking tour'],
      exclusions: ['Flights', 'Visa fees', 'Lunch and dinner'],
      coverImage: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800',
      images: ['https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800'],
      startDates: [new Date('2025-04-12'), new Date('2025-10-22')],
      availableSlots: 14,
      rating: 4.7,
      ratingsCount: 12,
      featured: true,
      status: 'Active',
      createdBy: admin._id
    },
    {
      title: 'Iceland Northern Lights Quest',
      description: 'Chase the magical aurora while exploring waterfalls, black sand beaches, and geothermal landscapes in Iceland’s wild beauty.',
      destination: 'Reykjavik',
      country: 'Iceland',
      duration: { days: 6, nights: 5 },
      price: { adult: 2799, child: 1799, currency: 'USD' },
      maxGroupSize: 12,
      difficulty: 'Moderate',
      category: 'Adventure',
      inclusions: ['Hotel stay', 'Breakfast', 'Northern lights tour', 'Golden Circle tour', 'Airport transfers'],
      exclusions: ['Flights', 'Thermal spa entry', 'Personal gear'],
      coverImage: 'https://images.unsplash.com/photo-1476611338391-6f395a0ebc7b?w=800',
      images: ['https://images.unsplash.com/photo-1476611338391-6f395a0ebc7b?w=800'],
      startDates: [new Date('2025-01-20'), new Date('2025-11-18')],
      availableSlots: 10,
      rating: 4.8,
      ratingsCount: 11,
      featured: true,
      status: 'Active',
      createdBy: admin._id
    },
    {
      title: 'Banff Rockies Adventure',
      description: 'Take in turquoise lakes, glacier views, and dramatic peaks in Canada’s Rockies with guided outdoor experiences in Banff.',
      destination: 'Banff',
      country: 'Canada',
      duration: { days: 7, nights: 6 },
      price: { adult: 2699, child: 1699, currency: 'USD' },
      maxGroupSize: 14,
      difficulty: 'Moderate',
      category: 'Mountain',
      inclusions: ['Lodge accommodation', 'Breakfast', 'Lake Louise excursion', 'National park fees', 'Guided hikes'],
      exclusions: ['Flights', 'Lunch and dinner', 'Personal equipment'],
      coverImage: 'https://images.unsplash.com/photo-1508264165352-258a6f82f5f1?w=800',
      images: ['https://images.unsplash.com/photo-1508264165352-258a6f82f5f1?w=800'],
      startDates: [new Date('2025-06-15'), new Date('2025-09-08')],
      availableSlots: 11,
      rating: 4.6,
      ratingsCount: 9,
      featured: false,
      status: 'Active',
      createdBy: admin._id
    },
    {
      title: 'Rio Carnival & Beaches Tour',
      description: 'Feel the rhythm of Rio with iconic beaches, mountain views, samba culture, and vibrant city energy for an unforgettable escape.',
      destination: 'Rio de Janeiro',
      country: 'Brazil',
      duration: { days: 6, nights: 5 },
      price: { adult: 2199, child: 1399, currency: 'USD' },
      maxGroupSize: 18,
      difficulty: 'Easy',
      category: 'Beach',
      inclusions: ['Beachfront hotel', 'Breakfast', 'Christ the Redeemer ticket', 'Sugarloaf cable car', 'City tour'],
      exclusions: ['Flights', 'Optional nightlife events', 'Travel insurance'],
      coverImage: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800',
      images: ['https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800'],
      startDates: [new Date('2025-02-10'), new Date('2025-08-20')],
      availableSlots: 17,
      rating: 4.5,
      ratingsCount: 10,
      featured: true,
      status: 'Active',
      createdBy: admin._id
    }
  ]);

  // Create sample bookings
  await Booking.create([
    {
      tour: tours[0]._id,
      user: user1._id,
      travelDate: new Date('2025-03-15'),
      adults: 2,
      children: 1,
      totalAmount: tours[0].price.adult * 2 + tours[0].price.child,
      status: 'Confirmed',
      paymentStatus: 'Paid',
      paymentMethod: 'Credit Card',
      contactInfo: { name: user1.name, email: user1.email, phone: user1.phone }
    },
    {
      tour: tours[1]._id,
      user: user2._id,
      travelDate: new Date('2025-02-20'),
      adults: 2,
      children: 0,
      totalAmount: tours[1].price.adult * 2,
      status: 'Pending',
      paymentStatus: 'Partial',
      paymentMethod: 'Bank Transfer',
      contactInfo: { name: user2.name, email: user2.email, phone: user2.phone }
    },
    {
      tour: tours[2]._id,
      user: user1._id,
      travelDate: new Date('2025-07-01'),
      adults: 1,
      children: 0,
      totalAmount: tours[2].price.adult,
      status: 'Confirmed',
      paymentStatus: 'Paid',
      paymentMethod: 'Online',
      contactInfo: { name: user1.name, email: user1.email, phone: user1.phone }
    }
  ]);

  console.log('\n✅ Database seeded successfully!');
  console.log('👤 Admin: admin@tourpro.com / admin123');
  console.log('👤 User: john@example.com / user123');
  console.log('👤 User: jane@example.com / user123');
  console.log(`🌍 ${tours.length} tours created\n`);

  mongoose.connection.close();
};

seed().catch((err) => {
  console.error('Seeding failed:', err);
  process.exit(1);
});
